### ISSUE TITLE
ECS

### ISSUE THREAD

**Issue by abueide** [littlektframework/littlekt#133]
Hi I love libgdx and I'm currently using libktx with Artemis odb. I'd love to convert my little bullet hell to littlekt to make it multiplatform but I think ECS architecture helps a lot for performance and maintainability in my use case. Would you mind touching on whether an ECS architecture would mesh well with the Godot style scene tree in littlekt? If not is it possible to use littlekt without it? Do you have any suggestions for a mpp kotlin ECS if one exists?

Thanks for your work excited to learn some more about littlekt and maybe get involved!

**Comment by LeHaine** [comment]
Hey! I have never personally used ECS so I am not entirely familiar on how it would mesh with the scene tree. It may be worth exploring. The only ECS multiplaform library that I know of is the one by Quillraven: https://github.com/Quillraven/Fleks/tree/kmp. This might be worth a shot trying to get going.
