### ISSUE TITLE
TTF workable example?

### ISSUE THREAD

**Issue by dmitrykolesnikovich** [littlektframework/littlekt#288]
I am not able to make TTF font render properly.  Could you please commit workable example?

**Comment by LeHaine** [comment]
Hello! Currently, there is no TTF rendering functionality available. There is functionality to load a TTF via `vfs["myFont.ttf"].readTtfFont()` which then can be used to render your own, if needed. There is plans to add back TTF rendering with WebGPU, either by generating a `BitmapFont` directly from a TTF, vector drawing, or even perhaps utilizing new functionality by generating a MSDF texture atlas for the font.

**Comment by dmitrykolesnikovich** [comment]
BTW in you work do you consider JavaScript implementations as reference to implement your own msdf generator for example https://github.com/Experience-Monks/msdf-bmfont?
