### ISSUE TITLE
Integrate ANGLE into LittleKt

### ISSUE THREAD

**Issue by LeHaine** [littlektframework/littlekt#58]
Since LittleKt is based on OpenGL and there are no plans to create a Metal renderer, we can look into integrating [ANGLE](https://github.com/google/angle) somehow into the project to work with Metal.

**Comment by Its-Kenta** [comment]
I'm actually curious if it's just me, but I played with ANGLE on my Mac Studio M2 Max and I found that ANGLE actually decreased my performance? This was done with Raylib as a test.

Are we sure that just wouldn't cause additional overhead?

**Comment by Its-Kenta** [comment]
If there is any testing to be done please let me know, free to run stuff and return back the numbers

**Comment by LeHaine** [comment]
Not longer applicable as the framework is using WebGPU now.
